***Objectif du projet:***
    
   1 - Exploration des données et analyse statistique sur Python.<br>
   2 - Modélisation à l’aide d’algorithme d’apprentissage supervisé <br>
   3 - Restitution des résultats en soutenance

In [1]:
### Importons les librairies necessaires au traitement 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
%matplotlib inline
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
### chargeons les données
df = pd.read_csv('listings.csv')

In [3]:
df.head()

,id,listing_url,scrape_id,last_scraped,name,description,neighborhood_overview,picture_url,host_id,host_url,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2577,https://www.airbnb.com/rooms/2577,20210410122610,2021-04-14,Loft for 4 by Canal Saint Martin,"100 m2 loft (1100 sq feet) with high ceiling, ...",NaN,https://a0.muscache.com/pictures/09da057c-0120...,2827,https://www.airbnb.com/users/show/2827,...,10.0,10.0,10.0,NaN,f,1,1,0,0,0.04
1,3109,https://www.airbnb.com/rooms/3109,20210410122610,2021-04-13,zen and calm,<b>The space</b><br />I bedroom appartment in ...,Good restaurants<br />very close the Montparna...,https://a0.muscache.com/pictures/baeae9e2-cd53...,3631,https://www.airbnb.com/users/show/3631,...,10.0,10.0,10.0,NaN,f,1,1,0,0,0.17
2,5396,https://www.airbnb.com/rooms/5396,20210410122610,2021-04-16,Explore the heart of old Paris,"Cozy, well-appointed and graciously designed s...","You are within walking distance to the Louvre,...",https://a0.muscache.com/pictures/52413/f9bf76f...,7903,https://www.airbnb.com/users/show/7903,...,10.0,10.0,9.0,7510402838018,f,1,1,0,0,1.65
3,7397,https://www.airbnb.com/rooms/7397,20210410122610,2021-04-16,MARAIS - 2ROOMS APT - 2/4 PEOPLE,"VERY CONVENIENT, WITH THE BEST LOCATION !<br /...",NaN,https://a0.muscache.com/pictures/67928287/330b...,2626,https://www.airbnb.com/users/show/2626,...,10.0,10.0,10.0,7510400829623,f,1,1,0,0,2.23
4,7964,https://www.airbnb.com/rooms/7964,20210410122610,2021-04-13,Large & sunny flat with balcony !,Very large & nice apartment all for you! <br /...,NaN,https://a0.muscache.com/pictures/4471349/6fb3d...,22155,https://www.airbnb.com/users/show/22155,...,10.0,10.0,10.0,7510903576564,f,1,1,0,0,0.05

In [4]:
df.shape

(63090, 74)

* comme on peut le voir, il y a:<br>
63090 lignes <br>
74 colonnes

In [5]:
### pour mner à bien notre analyse, verifions quel type de donner avons en face
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63090 entries, 0 to 63089
Data columns (total 74 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            63090 non-null  int64
 1   listing_url                                   63090 non-null  object
 2   scrape_id                                     63090 non-null  int64
 3   last_scraped                                  63090 non-null  object
 4   name                                          63028 non-null  object
 5   description                                   61681 non-null  object
 6   neighborhood_overview                         37484 non-null  object
 7   picture_url                                   63089 non-null  object
 8   host_id                                       63090 non-null  int64
 9   host_url                                      63090 non-null  object
 10  host_name                                     61336 non-null  object
 11  host_since                                    61336 non-null  object
 12  host_location                                 61207 non-null  object
 13  host_about                                    30791 non-null  object
 14  host_response_time                            21881 non-null  object
 15  host_response_rate                            21881 non-null  object
 16  host_acceptance_rate                          26064 non-null  object
 17  host_is_superhost                             61336 non-null  object
 18  host_thumbnail_url                            61336 non-null  object
 19  host_picture_url                              61336 non-null  object
 20  host_neighbourhood                            47048 non-null  object
 21  host_listings_count                           61336 non-null  float64
 22  host_total_listings_count                     61336 non-null  float64
 23  host_verifications                            63090 non-null  object
 24  host_has_profile_pic                          61336 non-null  object
 25  host_identity_verified                        61336 non-null  object
 26  neighbourhood                                 37484 non-null  object
 27  neighbourhood_cleansed                        63090 non-null  object
 28  neighbourhood_group_cleansed                  0 non-null      float64
 29  latitude                                      63090 non-null  float64
 30  longitude                                     63090 non-null  float64
 31  property_type                                 63090 non-null  object
 32  room_type                                     63090 non-null  object
 33  accommodates                                  63090 non-null  int64
 34  bathrooms                                     0 non-null      float64
 35  bathrooms_text                                62964 non-null  object
 36  bedrooms                                      50067 non-null  float64
 37  beds                                          62460 non-null  float64
 38  amenities                                     63090 non-null  object
 39  price                                         63090 non-null  object
 40  minimum_nights                                63090 non-null  int64
 41  maximum_nights                                63090 non-null  int64
 42  minimum_minimum_nights                        63077 non-null  float64
 43  maximum_minimum_nights                        63077 non-null  float64
 44  minimum_maximum_nights                        63077 non-null  float64
 45  maximum_maximum_nights                        63077 non-null  float64
 46  minimum_nights_avg_ntm                        63077 non-null  float64
 47  maximum_nights_avg_ntm                        63077 non-null  float64
 48  calendar_updated                              0 non-null      float64
 49  has_availability                              63090 non-null  object
 50  availability_30                               63090 non-null  int64
 51  availability_60                               63090 non-null  int64
 52  availability_90                               63090 non-null  int64
 53  availability_365                              63090 non-null  int64
 54  calendar_last_scraped                         63090 non-null  object
 55  number_of_reviews                             63090 non-null  int64
 56  number_of_reviews_ltm                         63090 non-null  int64
 57  number_of_reviews_l30d                        63090 non-null  int64
 58  first_review                                  47784 non-null  object
 59  last_review                                   47784 non-null  object
 60  review_scores_rating                          46641 non-null  float64
 61  review_scores_accuracy                        46592 non-null  float64
 62  review_scores_cleanliness                     46601 non-null  float64
 63  review_scores_checkin                         46576 non-null  float64
 64  review_scores_communication                   46595 non-null  float64
 65  review_scores_location                        46575 non-null  float64
 66  review_scores_value                           46577 non-null  float64
 67  license                                       21271 non-null  object
 68  instant_bookable                              63090 non-null  object
 69  calculated_host_listings_count                63090 non-null  int64
 70  calculated_host_listings_count_entire_homes   63090 non-null  int64
 71  calculated_host_listings_count_private_rooms  63090 non-null  int64
 72  calculated_host_listings_count_shared_rooms   63090 non-null  int64
 73  reviews_per_month                             47784 non-null  float64
dtypes: float64(23), int64(17), object(34)
memory usage: 35.6+ MB

In [6]:
### maitenant que savosn cela, verirfions s'il ya des donnes dupliqueés et manquantes et les ecarter
df.duplicated().sum()
df.drop_duplicates(inplace=True)

In [11]:
df.shape ### pas de données dupliquées

(63090, 74)

In [12]:
df.isnull()

,id,listing_url,scrape_id,last_scraped,name,description,neighborhood_overview,picture_url,host_id,host_url,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,False,False,False,False,False,False,True,False,False,False,...,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63085,False,False,False,False,False,False,False,False,False,False,...,True,True,True,False,False,False,False,False,False,True
63086,False,False,False,False,False,False,True,False,False,False,...,True,True,True,False,False,False,False,False,False,True
63087,False,False,False,False,False,False,True,False,False,False,...,True,True,True,False,False,False,False,False,False,True
63088,False,False,False,False,False,False,True,False,False,False,...,True,True,True,True,False,False,False,False,False,True
63089,False,False,False,False,False,False,True,False,False,False,...,True,True,True,False,False,False,False,False,False,True

In [14]:
df.isnull().sum()

id                                                  0
listing_url                                         0
scrape_id                                           0
last_scraped                                        0
name                                               62
                                                ...
calculated_host_listings_count                      0
calculated_host_listings_count_entire_homes         0
calculated_host_listings_count_private_rooms        0
calculated_host_listings_count_shared_rooms         0
reviews_per_month                               15306
Length: 74, dtype: int64

In [15]:
df.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'name', 'description',
       'neighborhood_overview', 'picture_url', 'host_id', 'host_url',
       'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

In [16]:
### supprimer les conlones inutiles à notre analyse 
df.drop(['name','id','host_name','last_review', 'scrape_id', 'last_scraped', 'host_id', 'host_url',
       'host_name', 'host_since', 'host_about', 'host_picture_url', 'host_listings_count', 'host_has_profile_pic', 'host_thumbnail_url', 'calendar_last_scraped',
        'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms',], axis=1, inplace=True)

In [17]:
df.head()

,listing_url,description,neighborhood_overview,picture_url,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_neighbourhood,...,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,reviews_per_month
0,https://www.airbnb.com/rooms/2577,"100 m2 loft (1100 sq feet) with high ceiling, ...",NaN,https://a0.muscache.com/pictures/09da057c-0120...,"Casablanca, Grand Casablanca, Morocco",within a day,50%,67%,f,République,...,100.0,10.0,10.0,10.0,10.0,10.0,10.0,NaN,f,0.04
1,https://www.airbnb.com/rooms/3109,<b>The space</b><br />I bedroom appartment in ...,Good restaurants<br />very close the Montparna...,https://a0.muscache.com/pictures/baeae9e2-cd53...,"Paris, Île-de-France, France",within a day,80%,0%,f,Alésia,...,100.0,10.0,10.0,10.0,10.0,10.0,10.0,NaN,f,0.17
2,https://www.airbnb.com/rooms/5396,"Cozy, well-appointed and graciously designed s...","You are within walking distance to the Louvre,...",https://a0.muscache.com/pictures/52413/f9bf76f...,"Istanbul, İstanbul, Turkey",within an hour,100%,92%,f,Saint-Paul - Ile Saint-Louis,...,90.0,9.0,9.0,10.0,10.0,10.0,9.0,7510402838018,f,1.65
3,https://www.airbnb.com/rooms/7397,"VERY CONVENIENT, WITH THE BEST LOCATION !<br /...",NaN,https://a0.muscache.com/pictures/67928287/330b...,"Paris, Île-de-France, France",within an hour,100%,83%,t,Le Marais,...,94.0,10.0,9.0,10.0,10.0,10.0,10.0,7510400829623,f,2.23
4,https://www.airbnb.com/rooms/7964,Very large & nice apartment all for you! <br /...,NaN,https://a0.muscache.com/pictures/4471349/6fb3d...,"Paris, Île-de-France, France",NaN,NaN,NaN,f,Gare du Nord - Gare de I'Est,...,96.0,10.0,10.0,10.0,10.0,10.0,10.0,7510903576564,f,0.05

In [19]:
df.drop(['listing_url', 'picture_url', 'review_scores_communication', 'license', 'instant_bookable' ], axis=1, inplace=True)

In [21]:
df.head()

,description,neighborhood_overview,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_neighbourhood,host_total_listings_count,host_verifications,...,number_of_reviews_ltm,number_of_reviews_l30d,first_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_location,review_scores_value,reviews_per_month
0,"100 m2 loft (1100 sq feet) with high ceiling, ...",NaN,"Casablanca, Grand Casablanca, Morocco",within a day,50%,67%,f,République,2.0,"['email', 'phone', 'reviews', 'jumio', 'govern...",...,0,0,2019-01-02,100.0,10.0,10.0,10.0,10.0,10.0,0.04
1,<b>The space</b><br />I bedroom appartment in ...,Good restaurants<br />very close the Montparna...,"Paris, Île-de-France, France",within a day,80%,0%,f,Alésia,1.0,"['email', 'phone', 'facebook', 'reviews']",...,0,0,2016-12-27,100.0,10.0,10.0,10.0,10.0,10.0,0.17
2,"Cozy, well-appointed and graciously designed s...","You are within walking distance to the Louvre,...","Istanbul, İstanbul, Turkey",within an hour,100%,92%,f,Saint-Paul - Ile Saint-Louis,1.0,"['email', 'phone', 'facebook', 'google', 'revi...",...,17,3,2009-06-30,90.0,9.0,9.0,10.0,10.0,9.0,1.65
3,"VERY CONVENIENT, WITH THE BEST LOCATION !<br /...",NaN,"Paris, Île-de-France, France",within an hour,100%,83%,t,Le Marais,4.0,"['email', 'phone', 'reviews', 'jumio', 'offlin...",...,4,1,2011-04-08,94.0,10.0,9.0,10.0,10.0,10.0,2.23
4,Very large & nice apartment all for you! <br /...,NaN,"Paris, Île-de-France, France",NaN,NaN,NaN,f,Gare du Nord - Gare de I'Est,0.0,"['email', 'phone', 'reviews', 'jumio', 'offlin...",...,0,0,2010-05-10,96.0,10.0,10.0,10.0,10.0,10.0,0.05

In [27]:
### Remplacer les valerus manquantes
df.isnull().sum()
df.dropna(how='any',inplace=True) 
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 0 entries
Data columns (total 50 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   description                   0 non-null      object
 1   neighborhood_overview         0 non-null      object
 2   host_location                 0 non-null      object
 3   host_response_time            0 non-null      object
 4   host_response_rate            0 non-null      object
 5   host_acceptance_rate          0 non-null      object
 6   host_is_superhost             0 non-null      object
 7   host_neighbourhood            0 non-null      object
 8   host_total_listings_count     0 non-null      float64
 9   host_verifications            0 non-null      object
 10  host_identity_verified        0 non-null      object
 11  neighbourhood                 0 non-null      object
 12  neighbourhood_cleansed        0 non-null      object
 13  neighbourhood_group_cleansed  0 non-null      float64
 14  latitude                      0 non-null      float64
 15  longitude                     0 non-null      float64
 16  property_type                 0 non-null      object
 17  room_type                     0 non-null      object
 18  accommodates                  0 non-null      int64
 19  bathrooms                     0 non-null      float64
 20  bathrooms_text                0 non-null      object
 21  bedrooms                      0 non-null      float64
 22  beds                          0 non-null      float64
 23  amenities                     0 non-null      object
 24  price                         0 non-null      object
 25  minimum_nights                0 non-null      int64
 26  maximum_nights                0 non-null      int64
 27  minimum_minimum_nights        0 non-null      float64
 28  maximum_minimum_nights        0 non-null      float64
 29  minimum_maximum_nights        0 non-null      float64
 30  maximum_maximum_nights        0 non-null      float64
 31  minimum_nights_avg_ntm        0 non-null      float64
 32  maximum_nights_avg_ntm        0 non-null      float64
 33  calendar_updated              0 non-null      float64
 34  has_availability              0 non-null      object
 35  availability_30               0 non-null      int64
 36  availability_60               0 non-null      int64
 37  availability_90               0 non-null      int64
 38  availability_365              0 non-null      int64
 39  number_of_reviews             0 non-null      int64
 40  number_of_reviews_ltm         0 non-null      int64
 41  number_of_reviews_l30d        0 non-null      int64
 42  first_review                  0 non-null      object
 43  review_scores_rating          0 non-null      float64
 44  review_scores_accuracy        0 non-null      float64
 45  review_scores_cleanliness     0 non-null      float64
 46  review_scores_checkin         0 non-null      float64
 47  review_scores_location        0 non-null      float64
 48  review_scores_value           0 non-null      float64
 49  reviews_per_month             0 non-null      float64
dtypes: float64(21), int64(10), object(19)
memory usage: 0.0+ bytes

In [23]:
df.dropna(how='any',inplace=True)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 0 entries
Data columns (total 50 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   description                   0 non-null      object
 1   neighborhood_overview         0 non-null      object
 2   host_location                 0 non-null      object
 3   host_response_time            0 non-null      object
 4   host_response_rate            0 non-null      object
 5   host_acceptance_rate          0 non-null      object
 6   host_is_superhost             0 non-null      object
 7   host_neighbourhood            0 non-null      object
 8   host_total_listings_count     0 non-null      float64
 9   host_verifications            0 non-null      object
 10  host_identity_verified        0 non-null      object
 11  neighbourhood                 0 non-null      object
 12  neighbourhood_cleansed        0 non-null      object
 13  neighbourhood_group_cleansed  0 non-null      float64
 14  latitude                      0 non-null      float64
 15  longitude                     0 non-null      float64
 16  property_type                 0 non-null      object
 17  room_type                     0 non-null      object
 18  accommodates                  0 non-null      int64
 19  bathrooms                     0 non-null      float64
 20  bathrooms_text                0 non-null      object
 21  bedrooms                      0 non-null      float64
 22  beds                          0 non-null      float64
 23  amenities                     0 non-null      object
 24  price                         0 non-null      object
 25  minimum_nights                0 non-null      int64
 26  maximum_nights                0 non-null      int64
 27  minimum_minimum_nights        0 non-null      float64
 28  maximum_minimum_nights        0 non-null      float64
 29  minimum_maximum_nights        0 non-null      float64
 30  maximum_maximum_nights        0 non-null      float64
 31  minimum_nights_avg_ntm        0 non-null      float64
 32  maximum_nights_avg_ntm        0 non-null      float64
 33  calendar_updated              0 non-null      float64
 34  has_availability              0 non-null      object
 35  availability_30               0 non-null      int64
 36  availability_60               0 non-null      int64
 37  availability_90               0 non-null      int64
 38  availability_365              0 non-null      int64
 39  number_of_reviews             0 non-null      int64
 40  number_of_reviews_ltm         0 non-null      int64
 41  number_of_reviews_l30d        0 non-null      int64
 42  first_review                  0 non-null      object
 43  review_scores_rating          0 non-null      float64
 44  review_scores_accuracy        0 non-null      float64
 45  review_scores_cleanliness     0 non-null      float64
 46  review_scores_checkin         0 non-null      float64
 47  review_scores_location        0 non-null      float64
 48  review_scores_value           0 non-null      float64
 49  reviews_per_month             0 non-null      float64
dtypes: float64(21), int64(10), object(19)
memory usage: 0.0+ bytes

In [26]:
df

Empty DataFrame
Columns: [description, neighborhood_overview, host_location, host_response_time, host_response_rate, host_acceptance_rate, host_is_superhost, host_neighbourhood, host_total_listings_count, host_verifications, host_identity_verified, neighbourhood, neighbourhood_cleansed, neighbourhood_group_cleansed, latitude, longitude, property_type, room_type, accommodates, bathrooms, bathrooms_text, bedrooms, beds, amenities, price, minimum_nights, maximum_nights, minimum_minimum_nights, maximum_minimum_nights, minimum_maximum_nights, maximum_maximum_nights, minimum_nights_avg_ntm, maximum_nights_avg_ntm, calendar_updated, has_availability, availability_30, availability_60, availability_90, availability_365, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, first_review, review_scores_rating, review_scores_accuracy, review_scores_cleanliness, review_scores_checkin, review_scores_location, review_scores_value, reviews_per_month]
Index: []

[0 rows x 50 columns]